# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
python:
  # If more versions are added here, they should also be added to the
  # exclude: block below.
  - 2.5
  - 2.6
  - 2.7
env:
  # Hack: we actually test:
  #   - all versions of python with numpy 1.6.1
  #   - python *2.4* with numpy 1.2.1 (this is the RHEL5 configuration)
  # but travis doesn't support python 2.4, and never will:
  #   https://github.com/travis-ci/travis-ci/issues/485
  # So what we do is add 1.2.1 to the build matrix, then exclude it on
  # all-but-one python version, and then for that one version we don't
  # actually use the system python, but instead build 2.4 and use it.
  - NUMPY_VER=1.2.1
  # Currently the latest release:
  - NUMPY_VER=1.6.2
matrix:
  exclude:
    - python: 2.6
      env: NUMPY_VER=1.2.1
    - python: 2.7
      env: NUMPY_VER=1.2.1
before_install:
  - mkdir builds
  - pushd builds
  # This has to be on a single "virtual line" because of how Travis
  # munges each line before executing it to print out the exit status.
  # It's okay for it to be on multiple physical lines, so long as you remember:
  # - There can't be any leading "-"s
  # - All newlines will be removed, so use ";"s
  - if [ "${NUMPY_VER}" == "1.2.1" ]; then
      deactivate; 
      ../.travis-make-py24-virtualenv.sh $PWD/py24-ve;
      source $PWD/py24-ve/bin/activate;
      fi
  - pip install nose
  # pip install coverage
  - python -V
  - popd
install:
  - python setup.py install
script:
  # We change directories to make sure that python won't find the copy
  # of charlton in the source directory.
  - mkdir empty
  - cd empty
  - INSTALLDIR=$(python -c "import os; import numpy; print(os.path.dirname(numpy.__file__))")
  - export PYTHONWARNINGS=default
  - python ../tools/test-installed-numpy.py
  # - coverage run --source=$INSTALLDIR --rcfile=../.coveragerc $(which python) ../tools/test-installed-numpy.py
  # - coverage report --rcfile=../.coveragerc --show-missing

